### ISSUE TITLE
Responsiveness bug on mobile devices

### ISSUE THREAD

**Issue by MarceloPedra** [jameskoster/woocommerce-cart-tab#20]
Hi! I noticed you don't answer on WP.org forums, so I'll copy here a problem I noticed with mobile screens:

When you use this plugin on mobile devices, it just cover almost all the screen. I tested it on iPhone and using the excelent Google Chrome extension Responsive Web Design Tester (https://chrome.google.com/webstore/detail/responsive-web-design-tes/objclahbaimlfnbjdeobicmmlnbhamkg) and it's true: no matter what device you emulate, the tab is always too big. Giant, actually.

Is there any way to fix this? I bet it's a CSS media query thing, but I'm not that good with it to fix this.

Best regards

**Comment by jameskoster** [comment]
Could you show me a screenshot? It shouldn't be so big, the font size is just inherited from the theme.

**Comment by MarceloPedra** [comment]
Yes, you can try it yourself: http://enviaregalo.com/
The tab start to be giant when you navigate with iPhone 4 or 5 in portrait mode. And in smaller screens it looks even bigger.

Below I post two screen captures:
https://docs.google.com/file/d/0B4ZIdz9VEIQGZFoxNlRESzkzWUE/edit?usp=drivesdk
https://docs.google.com/file/d/0B4ZIdz9VEIQGMlhYTko1TnJyY1k/edit?usp=drivesdk

On landscape mode it looks ok, but there are a lot of people dummy enough to not figure out they can rotate the device... and those are lost sales :(

Is there any possibility to size down the tab a bit when the screen size is too small?

Thank you!

**Comment by jameskoster** [comment]
It doesn't actually increase in size for me, it stays the same.

All I can suggest to make it smaller would be to reduce the padding a bit.

Something like: `.cart-tab a.cart-parent { padding: .618em; }`.

Cheers

**Comment by MarceloPedra** [comment]
Great, interesting approach. I completed the code by wrapping it with a media query...

@media only screen and (max-width: 980px){
   .cart-tab a.cart-parent { padding: .618em; }
}

Not bad at all. And for the rest of the humans, they should be savvy enough to rotate their screns 90º :)

**Comment by jameskoster** [comment]
:-)
