### ISSUE TITLE
Does it work in a WordPress multisite installation?

### ISSUE THREAD

**Issue by fakeartist** [jameskoster/woocommerce-cart-tab#21]
I cannot see the cart tab options in the dashboard in my multisite (while it works perfect in a standard one-site WordPress installation). Any thoughts? Any one else with the same problem?

**Comment by fakeartist** [comment]
Just found a temporary fix. Open the file

'woocommerce-cart-tab/cart-tab.php'

and comment line 20

//if (in_array('woocommerce/woocommerce.php', apply_filters('active_plugins', get_option('active_plugins')))) {

and line 179 (the if closing bracket)

//}

The cart tab is back again!

Seems that the filter used hear doesn't work on a multisite. I don't know if it is needed also.

**Comment by jameskoster** [comment]
The check is required to make sure the plugin only loads if WooCommerce is active. 

WooCommerce doesn't _officially_ support multisite yet. I'll investigate this further when it does.
