### ISSUE TITLE
Only show it when pointer is over cart link on menu

### ISSUE THREAD

**Issue by Extraterrestre** [jameskoster/woocommerce-cart-tab#23]
Hi! I just installed this plugin and I can't find it's specific options and I need to hide this tab to show it when the pointer is over the cart icon on the main menu. How can I do this? Is the an option to do this or something similar? Thank you!!!

**Comment by jameskoster** [comment]
Hey,

There's not an option to do this I'm afraid as it's impossible for the plugin to know what class/id the theme might use for the cart link in the main nav. You'd need to add some javascript to your theme to handle this.

Sorry about that!

**Comment by Extraterrestre** [comment]
Thank you!! I just used javascript and it worked ^^
