### ISSUE TITLE
Disable on home page

### ISSUE THREAD

**Issue by DaveyD** [jameskoster/woocommerce-cart-tab#24]
Hi, first off, thanks for this plugin - it's exactly what I was looking for!
Secondly,iIs it possible to disable the cart tab on the home page?
I want it to be on all pages besides the home page

Thank You!

**Comment by jameskoster** [comment]
You'd need to edit the plugin I'm afraid. It'd be easier to just use some CSS to hide it on the homepage.

Please post on the wordpress.org forums for support, github isn't the place to discuss these things :)

Cheers

**Comment by DaveyD** [comment]
Ok, thanks
I was actually asking for an added option that's why I posted here. But I guess if it's possible to do it on my end then it's not necessary

Thanks
