### ISSUE TITLE
Catalog tab, WooCommerce settings

### ISSUE THREAD

**Issue by Tanjitsu** [jameskoster/woocommerce-cart-tab#33]
I dont seem to have an option for "Catalog" under "WooCommerce->settings"

Using WooCommerce Version 2.6.14 

There are options (Catalog tab, WooCommerce settings) to display the cart tab on the right or the left, to use a light or dark skin to match your theme and to display the cart widget on hover or not.

**Comment by Tanjitsu** [comment]
Just found your Updated notes for 
* New - Display controls moved to the Customizer.

The new version has a radically new look, using the background dimmer and full length sidebar.
I much preferred the previous version styling / display.
Would it be possible to add this as a Customizer option, to choose between the previous style and the new ?

**Comment by jameskoster** [comment]
No I won't be adding that as an option - too much to maintain and un-necessary bloat.

If you prefer the previous version I recommend just rolling back and using that :)
