### ISSUE TITLE
Change the bag to cart

### ISSUE THREAD

**Issue by vi0lepat** [jameskoster/woocommerce-cart-tab#34]
hello there.. 
i would like to know if it is possible to change the bag icon to cart icon and how.

Thank you and continue the good job!!

**Comment by jameskoster** [comment]
I might add this as an option in the future, but for now you'll need to customise this yourself.

**Comment by vi0lepat** [comment]
Thank you for your answer.

Can  i ask how can i change it? is it possible to enlighten me with the code i need to change?

thank you one more time

**Comment by jameskoster** [comment]
The code for the icon is here; https://github.com/jameskoster/woocommerce-cart-tab/blob/master/includes/cart-tab-templates.php#L18

You'd need to create a new svg to replace that.

**Comment by vi0lepat** [comment]
thank you for the help!! ;) now time to make the cart visible even when it is empty!! ;)
