### ISSUE TITLE
Unable to hide cart when no items are in it

### ISSUE THREAD

**Issue by KyleStilkey** [jameskoster/woocommerce-cart-tab#35]
Since the new 1.0 update, there is no longer an option to hide the cart tab when there is no items in the cart. I'd like to see this option return as this helped keep websites clean and the only people that would see this are the ones that shop on my website.

Other than that, I love the work you've done and I'm very happy with the new update!

**Comment by jameskoster** [comment]
Whoops, I meant to hide the cart by default when it's empty, I'll fix that in the next update.

**Comment by KyleStilkey** [comment]
Thanks man! Love the update, was much needed. Keep up the work!
