### ISSUE TITLE
WooCommerce 2.7 compatibility

### ISSUE THREAD

**Issue by webmandesign** [jameskoster/woocommerce-cart-tab#39]
Hi,

First, thank you for building this awesome plugin!

I have a question about future WooCommerce compatibility. As new [WC 2.7 is planned for 14th March 2017](https://woocommerce.wordpress.com/2017/02/28/woocommerce-2-7-release-candidate/), I would like to know if this plugin is going to support that version without any deprecation notices or PHP errors. Do you plan updating the plugin for WC 2.7?

Thanks!

Oliver

**Comment by webmandesign** [comment]
Hi,

I have fixed the WC2.7 compatiblity in pull request #40

Please, update the plugin so it is compatible.

Thank you!

**Comment by jameskoster** [comment]
Cheers!

**Comment by webmandesign** [comment]
Hi, Thank you for merging this fix/update! Could you please update your [WooCommerce Product Image Flipper](https://github.com/jameskoster/woocommerce-product-image-flipper/) plugin too? I've also [proposed an update there](https://github.com/jameskoster/woocommerce-product-image-flipper/issues/7). Thanks!
