### ISSUE TITLE
cart tab doesn't appear on iphone

### ISSUE THREAD

**Issue by Stacyhendrie** [jameskoster/woocommerce-cart-tab#41]
I add something to the cart and see "view cart" but once I leave that screen and return the "view cart" disappears and the tab that I see on the website it not visible so there is no way to get to the cart.  I have to add something to the cart so that "view cart" appears and then I can click it.  Why no tab?

**Comment by jameskoster** [comment]
https://github.com/jameskoster/woocommerce-cart-tab/issues/37

It's on the to-do list :)
