### ISSUE TITLE
Cart Button not shown up

### ISSUE THREAD

**Issue by DevTestCRM** [jameskoster/woocommerce-cart-tab#42]
As per installation
![screenshot_19](https://cloud.githubusercontent.com/assets/28685865/26033296/e83803ac-38c2-11e7-8130-d039d650a42a.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/28685865/26033297/e9493f4a-38c2-11e7-81e8-712c321c43c2.png)

 instruction in your wp plugin we can not seen any catalog tab in setting,and also not cart button shown up in store
please guide me is something we are missing
Thanks in advance

**Comment by jameskoster** [comment]
Looks like the installation copy needs an update. The settings now live in the Customizer.

**Comment by kirpi-it** [comment]
Hi James,
I cannot find any Cart Tab in the Customizer. I also updated to your most recent version yesterday, yet no way to find it. Would you please have any clue?
Thanks!

**Comment by jameskoster** [comment]
Are you using the Storefront theme? There's no options for Storefront as the integration is built-in.
