### ISSUE TITLE
How to enable ajax remove product.

### ISSUE THREAD

**Issue by Chowix** [jameskoster/woocommerce-cart-tab#43]
Hello,

i have ajax remove product on cart but i don't have on WooCommerce Cart Tab widget. How can i enable ajax in WooCommerce Cart Tab ?

Dawid

**Comment by jameskoster** [comment]
Is that a separate widget? This plugin simply calls the WooCommerce core cart widget. If you're using a different one you'll need to modify the plugin to use the same one.

Please post this query on the WordPress.org support forums. Github is for bug reports :)

Cheers
