### ISSUE TITLE
Page shift when opening tab

### ISSUE THREAD

**Issue by papercrate** [jameskoster/woocommerce-cart-tab#48]
I am now noticing that the entire main content of the site shifts slightly to the right (approximately 10 pixels) when opening the cart tab, and then it shifts back when closing. Not sure if this is a rendered width issue on the main content or what? Issues occurs on Chrome and Safari as tested. A curious development since updating to Storefront 2.2.8 (running WooCommerce 3.3.1, just FYI). It may have been happening before, but I don't recall.

You can see the example here: [http://analogbook.com/aqjp8h3o2g/](http://analogbook.com/aqjp8h3o2g/).

**Comment by jameskoster** [comment]
Doesn't seem to be happening now?

**Comment by papercrate** [comment]
Nah, it's still happening. Both Chrome and Safari. If you look on the left side of the webpage when opening and closing the cart tab you can see the 10 pixel shift.

**Comment by jameskoster** [comment]
Not happening here in Chrome. Weird.

![chrome](https://cldup.com/uG9ukVJ8yl.gif)

**Comment by papercrate** [comment]
Ah, well good to know! Maybe just something quirky on my end.
