### ISSUE TITLE
How to show cart even if empty

### ISSUE THREAD

**Issue by prafullwizorbit** [jameskoster/woocommerce-cart-tab#49]
Hi 
    I want to show cart even if empty, is there any setting to show the cart even may be empty ?
Thanks

**Comment by jameskoster** [comment]
I recommend searching/posting on the [support forum](https://wordpress.org/support/plugin/woocommerce-cart-tab).

**Comment by prafullwizorbit** [comment]
OK
      I have solved this by css.
Thanks
