### ISSUE TITLE
Last version 1.1.2 does not empty the cart

### ISSUE THREAD

**Issue by kirpi-it** [jameskoster/woocommerce-cart-tab#52]
Since yesterday, after updating to the 1.1.2 version, when clicking on the red point in the Cart Tab it *seems* that the product has been removed from the cart. But if you visit the real cart page, it's still there! :-|

**Comment by jameskoster** [comment]
Hey, I'm unable to replicate this. It's also very unlikely that this plugin would cause that to happen as both the removal feature and the core cart are part of WooCommerce core which this plugin doesn't touch.

Try adding a cart widget to your sidebar and see i that behaves the same way. Sounds like it could be a cache issue.
